# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Leonard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(737, 439)
        MainWindow.setStyleSheet("color: rgb(193, 193, 193);\n"
"background-color: rgb(33, 33, 33);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setStyleSheet("border: 1px solid grey;")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FrameParameters = QtWidgets.QFrame(self.MainFrame)
        self.FrameParameters.setMinimumSize(QtCore.QSize(300, 0))
        self.FrameParameters.setMaximumSize(QtCore.QSize(300, 16777215))
        self.FrameParameters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameParameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameParameters.setObjectName("FrameParameters")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FrameParameters)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PushButtonApply = QtWidgets.QPushButton(self.FrameParameters)
        self.PushButtonApply.setStyleSheet("background-color: rgb(80, 80, 80);\n"
"color: rgb(255, 221, 187);\n"
"border: 2px solid grey;\n"
"font: 10pt \"Consolas\";")
        self.PushButtonApply.setObjectName("PushButtonApply")
        self.verticalLayout_2.addWidget(self.PushButtonApply)
        self.TextEditParameters = QtWidgets.QTextEdit(self.FrameParameters)
        self.TextEditParameters.setObjectName("TextEditParameters")
        self.verticalLayout_2.addWidget(self.TextEditParameters)
        self.horizontalLayout.addWidget(self.FrameParameters)
        self.FrameGraphics = QtWidgets.QFrame(self.MainFrame)
        self.FrameGraphics.setMinimumSize(QtCore.QSize(0, 0))
        self.FrameGraphics.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FrameGraphics.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameGraphics.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameGraphics.setObjectName("FrameGraphics")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FrameGraphics)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.WiMatPlotLib = QtWidgets.QWidget(self.FrameGraphics)
        self.WiMatPlotLib.setObjectName("WiMatPlotLib")
        self.horizontalLayout_2.addWidget(self.WiMatPlotLib)
        self.horizontalLayout.addWidget(self.FrameGraphics)
        self.verticalLayout.addWidget(self.MainFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 737, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PushButtonApply.setText(_translate("MainWindow", "Apply"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
